# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scheduler?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Kpv4hX7wP.fgje
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      enabled: true
      location: /Users/finn/tmp
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8081

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

uofg:
  scheduler:
    jwt:
      # 加密秘钥
      secret: f4e2e52034348f86b67cde581c0f9eb5
      # token有效时长，7天，单位秒
      expire: 604800
      header: token